### ISSUE TITLE
golang:alpine missing packages

### ISSUE THREAD

**Issue by edieship** [docker-library/golang#115]
Hi,

The golang:alpine image is missing packages. 

/go # apk info
WARNING: Ignoring APKINDEX.167438ca.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.a2e6dac0.tar.gz: No such file or directory
musl
busybox
alpine-baselayout
alpine-keys
zlib
libcrypto1.0
libssl1.0
apk-tools
scanelf
musl-utils
libc-utils
ca-certificates

Some packages listed in the Dockerfile such as gcc, bash, musl-dev, openssl are missing. Seems like a apk update needs to be run prior to the apk add.

**Comment by yosifkit** [comment]
Those tools are removed on purpose just a little [further down in the Dockerfile](https://github.com/docker-library/golang/blob/53424cae6af3b17e93057698496c95d026bd65b2/1.7/alpine/Dockerfile#L31).  Also, `apk add --no-cache` does an `apk update` but deletes the cache immediately so that it won't take space in the final image.  Related to https://github.com/docker-library/golang/pull/69.
> To minimize image size, it's uncommon for additional related tools (such as git or bash) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile.
> \- https://github.com/docker-library/docs/tree/6094401f0eec2ac2fefbfe7c0f37ed3f023e1e5e/golang#golangalpine

**Comment by edieship** [comment]
Than you yosifkit, I overlooked the apk del. 
This can be closed now.
