### ISSUE TITLE
Build docker-hub images periodically

### ISSUE THREAD

**Issue by mtekel** [docker-library/golang#118]
Hi,

it would be nice if you were building the images you provide at https://hub.docker.com/_/golang/ periodically (daily?). This way we could get latest OS fixes when pulling the images. Currently, for example, alpine image was build 19 days ago and thus doesn't contain some fixes that have been already released, e.g. https://bugs.alpinelinux.org/issues/6374

When I now pull image directly from docker hub, or have my image built using your image, I will get older OS version which still contains the bug.

It also seems that periodical building would be good to apply any security fixes base OS images might have had since last build....

**Comment by yosifkit** [comment]
We rebuild all descendant images when a base image like `alpine:3.4` is updated.  To see when updates to images are added follow the [official-images](https://github.com/docker-library/official-images) repo; specifically watch the `library/` folder.  The alpine base images have not been updated since about Oct 18, 2016; I don't see `xargs` changed in the [diff](https://github.com/docker-library/official-images/pull/2266#issuecomment-254616289) so I think the fix you noted was not included in their update.  Since it is really an issue with the alpine image, you may want to raise an issue in their repo: https://github.com/gliderlabs/docker-alpine/issues.

**Comment by mtekel** [comment]
Hm,

you are right. I am not sure what version of alpine image I was running. I thought it was official alpine with the fix, but I got the image probably from elsewhere. 

But what about security updates? The OS can get patched without any docker files in git being updated...
E.g. when I 'apk update' and then 'apk upgrade' on the base alpine (or your derived golang) image, I get fixed musl and xargs starts working correctly...

**Comment by yosifkit** [comment]
No, we don't run the base images to add security updates to the installed packages; that is up to the maintainer of the image to release an updated base image.  Any of the official images only install new dependencies and let the base image worry about packages bundled in the base.  With the layered file system of docker images, it'll double the storage of any packages that are updated in a later layer.

**Comment by mtekel** [comment]
My point was, when you only rebuild on base OS Docker file change, then it can be quite some time before it is changed. Meanwhile there can be several new base image releases. When I take your docker file and build it, I get the latest base image of the OS. But if I do docker pull from your repository of built images, I get OS base image that was latest when you did your build. 

If you would trigger your builds instead on new base OS images being released on docker hub, then you always have the latest base OS....

Nevertheless this also doesn't mean periodically, but it would mean more recent OS without too much overhead.
