### ISSUE TITLE
"Host key verification failed." when git cloning public GitHub repos

### ISSUE THREAD

**Issue by mcandre** [docker-library/golang#148]
When I try to `RUN git clone git@github.com:edenhill/librdkafka.git` from the golang:1.7 base, Docker reports:

```
Cloning into 'librdkafka'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Could `golang:1.7` have old or missing entries for GitHub's public key?

**Comment by tianon** [comment]
This would be because using the `git@github.com:...` syntax ends up using SSH to clone, and inside the container, your private key is not available.  You'll want to use `RUN git clone https://github.com/edenhill/librdkafka.git` instead.

**Comment by aabes** [comment]
The error in this case is about github.com host key, not private key.
see: http://debuggable.com/posts/disable-strict-host-checking-for-git-clone:49896ff3-0ac0-4263-9703-1eae4834cda3

**Comment by asim42** [comment]
@aabes This Solved my problem, thanks!

**Comment by yosifkit** [comment]
@asim42, I would highly recommend against `StrictHostKeyChecking no` since it is insecure. The solutions is to either:

- clone via https if it a public project: `git clone https://github.com/docker-library/golang`
- echo the github host key into known_hosts: `ssh-keyscan github.com >> ~/.ssh/known_hosts`
  - you can then compare that to the fingerprints from [github](https://help.github.com/articles/github-s-ssh-key-fingerprints/): `ssh-keyscan -t rsa github.com | ssh-keygen -lf -`
  - [serverfault.com link](https://serverfault.com/a/856211)
