### ISSUE TITLE
net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by sulthonzh** [docker-library/golang#176]
hi, i have a problem when use golang1.9 image, 
first error :

> net/http: TLS handshake timeout

then : 

> RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.

but golang1.8 image work fine

**Comment by tianon** [comment]
This definitely needs more debugging/detective work before it can be considered actionable.  Did you look for similar issues reported against Go 1.9 elsewhere (Docker related or not)?  Did you try installing different packages, in case Go is simply missing something?  Do you have a simple example application with reproduces the issue in a simple way?  The error message is an OK start, but there's more work to be done to get to the bottom of why it's happening.  How exactly are you using the `golang:1.9` image?  Are you using the Alpine variant or the Debian variant?  What does your `go build` line look like?

In the future, these sorts of questions/requests would be more appropriately posted first to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker), then an issue (or even a PR!) filed here once sufficient information has been gathered to determine either the root cause or the solution (if it's something that can be traced to the image, and not simply a problem with your application code or Go upstream).
