### ISSUE TITLE
pkg_config_path error on building with docker

### ISSUE THREAD

**Issue by nupurbansal8** [docker-library/golang#185]
When I am building an image for my golang application through docker, I am getting the following error:

**# pkg-config --cflags oci8
Package oci8 was not found in the pkg-config search path. Perhaps you should add the directory containing `oci8.pc' to the PKG_CONFIG_PATH environment variable No package 'oci8' found pkg-config: exit status 1**

I have set the environment variable in my Dockerfile also. But still the issue persists. My Dockerfile is:

_FROM golang:1.9 
ARG app_env 
ENV APP_ENV $app_env
ENV GOPATH /home/nupur/mapi-go 
ENV PKG_CONFIG_PATH /home/nupur/mapi-go 
ENV ORACLE_HOME /usr/include/oracle/11.2/client64 
ENV LD_LIBRARY_PATH /usr/lib/oracle/11.2/client64/lib 
WORKDIR /home/nupur/mapi-go/src/DockerApp/blDocker 
ADD . . 
RUN go build /home/nupur/mapi-go/src/DockerApp/blDocker/launch.go 
ENTRYPOINT ["./launch"] 
EXPOSE 8093_

Please suggest a solution.

**Comment by yosifkit** [comment]
Does `/home/nupur/mapi-go/` in the container contain an `oci8.pc` file as described over in [mattn/go-oci8](https://github.com/mattn/go-oci8/tree/73e70e9fc52baed56e26e53fb22c21a913e69490#example-for-linux)? 

Does `/usr/include/oracle/11.2/client64` and `/usr/lib/oracle/11.2/client64/lib` contain the necessary Oracle bits (there was no mention of installing it in the Dockerfile)?

Since this is not really an issue with the image, but an issue with using a specific library, I am going to close.  In the future, it'd be better to post questions like this in [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
