### ISSUE TITLE
running a golang branch in docker

### ISSUE THREAD

**Issue by gedw99** [docker-library/golang#189]
I want to compile golang from source within docker.

Is there a docker image designed for this ?. Basically self bootstrapping.

**Comment by yosifkit** [comment]
The alpine images compile go while applying some alpine specific patches:

https://github.com/docker-library/golang/blob/2a2ed6815477a54b7772d45c6e153dcc51f72ef9/1.8/alpine3.5/Dockerfile#L37-L47

And we used to compile go for 1.4 and below since there were not any binary releases.

https://github.com/docker-library/golang/blob/bcc3800fbed7f5116ff27ae82e0d881efd50aa69/1.4/Dockerfile#L13-L17
