### ISSUE TITLE
[feature request]: Please add the dep tool to the image

### ISSUE THREAD

**Issue by agnivade** [docker-library/golang#204]
Currently, for CI purposes, one needs to additionally download the `dep` tool. It would be great if it was packaged by default with the image.

FWIW - `yarn` is packaged inside the `node` image.

**Comment by tianon** [comment]
I'm inclined to _not_ include this for the reasons pointed out by the `dep` project:

https://github.com/golang/dep

> `dep` is the official _experiment_, but not yet the official tool. Check out the [Roadmap](https://github.com/golang/dep/wiki/Roadmap) for more on what this means!

https://github.com/golang/dep/wiki/Roadmap

> The goal with `dep` is to be absorbed into the `go` toolchain.

For users who want to play with it before it's officially included in the standard distribution of Go (which will make it naturally available here with no functional changes to the structure of the image), it should be fairly trivial to grab it from https://github.com/golang/dep/releases or via `go get -u github.com/golang/dep/cmd/dep` for those feeling adventurous enough to use master.

What I don't want to do is inadvertently discourage folks from trying `dep` alternatives because we chose a winner before it was actually official, and we're definitely not going to include `godep` and/or other alternatives.

In the case of the `node` image, NPM is included in the standard distribution of Node.js, and it was a decision of the official upstream Node.js working group responsible for the Docker images to include Yarn as well.

In our case, we don't speak for the Go community at all -- we're simply packagers.

**Comment by agnivade** [comment]
FWIW, `dep` is more or less the standard package manager in the Go community. Even other package managers suggest to use `dep`. _Until_ it is merged with the toolchain, this is the recommended tool to use. 

Yes, it is trivial to to grab and install it. That is what I am doing currently. But small things like these make our lives just a little bit easier. :smile: 

But at the end of the day, you are the stakeholder of the project. And I think you have already made your decision. In that case, feel fee to close this.

**Comment by tianon** [comment]
https://research.swtch.com/vgo-intro is a great article rsc's put out today that's related to this :+1:

**Comment by AndrienkoAleksandr** [comment]
Any news?

**Comment by tianon** [comment]
Yep, `go mod` is official, included in the standard distribution, and supercedes `dep`.
