### ISSUE TITLE
Error running a docker API - curl: (56) Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by dharnnie** [docker-library/golang#210]
Hi,

I am building a simple API with go and I am trying to deploy with docker. The process builds, and when I run (from docker) the app starts.

But when I try to access endpoints with curl, I get this error (curl: (56) Recv failure: Connection reset by peer). 

I have this snippet in my main function:

`port := os.Getenv("PORT")
	if port == "" {
		port = "2000"
	}`
and I then bind to listen and serve:
Like so:

`err := http.ListenAndServe(":"+port, nil)
	if err != nil {
		//log.Fatal("Server error", err)
	}`
I am not sure the error is coming from here, but I have tried to remove that first bit of code and leave the port empty, still makes no difference.

The API works without docker (with those snippets) but would not work if I try to run with docker.

**Comment by tianon** [comment]
This seems like it's probably either an issue with your code somehow, or an issue with the networking provided by Docker.  I'd recommend trying [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker), or even a Go-specific community forum to get further help debugging.

I can confirm that I've successfully used this image to build and run Go-based applications with long-lived TCP and UDP listeners and haven't run into any significant issues (especially since the non-Alpine variants of this image are providing the officially released upstream binaries from https://golang.org/dl/).  Sorry we can't be of more help!

**Comment by Purushotham233** [comment]
@wglambert were you able to figure out the issue? Am facing the same.
