### ISSUE TITLE
Debian sid with Go 1.11 and 1.10

### ISSUE THREAD

**Issue by avelino** [docker-library/golang#244]
Is having a Debian Sid version important to the project?

I did repository (@nuveo need), if it is interesting to the project I can send PR here.

https://github.com/nuveo/docker-golang

**Comment by yosifkit** [comment]
Given the following I would not offer tags based on `sid` unless there is no other way to offer the main software of the image, ie golang itself.

> sid is subject to massive changes and in-place library updates. This can result in a very unstable system which contains packages that cannot be installed due to missing libraries, dependencies that cannot be fulfilled etc. Use it at your own risk!
>
> https://www.debian.org/releases/sid/

The only images that are `FROM debian:sid` are `openjdk:10` and `openjdk:11` (and images that build from them) since that *was* one of the only ways to get the newer jdk without multi-hour compile times (https://github.com/docker-library/openjdk/issues/150#issuecomment-338713389, https://github.com/docker-library/openjdk/issues/237).  They are still offered since the new alternative is based on Oracle Linux (https://github.com/docker-library/openjdk/pull/235).
