### ISSUE TITLE
Alpine: go get triggers cgo warning, even though cgo unused

### ISSUE THREAD

**Issue by mcandre** [docker-library/golang#268]
I can build and run Go binaries with Go 1.11 provided by Alpine 3.9. However, when `go get` runs, an ugly warning is emitted:

```console
$ go get github.com/mcandre/go-ios7crypt/...
# github.com/mcandre/go-ios7crypt/cmd/ios7crypt
loadinternal: cannot find runtime/cgo
```

Strange, as my Go project does not use cgo, it uses pure Go.

For context, I am using the go, git, and musl-dev OS packages provided for Alpine 3.9.

Example Dockerfile with this configuration:

```docker
FROM alpine:3.9
ENV GOPATH /go
ENV PATH $PATH:$GOPATH/bin
RUN apk add -U go git musl-dev
```

**Comment by wglambert** [comment]
>FROM alpine:3.9

That isn't the `golang` image for this repo

```console
$ docker build -t golang:alpine - << EOF
> FROM golang:alpine
> RUN apk add --no-cache git musl-dev
> EOF
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM golang:alpine
 ---> d4953956cf1e
Step 2/2 : RUN apk add --no-cache git musl-dev
 ---> Using cache
 ---> 83ff7cc38f87
Successfully built 83ff7cc38f87
Successfully tagged golang:alpine

$ docker run -it --rm golang:alpine sh
/go # go get github.com/mcandre/go-ios7crypt/...
/go # ls
bin  pkg  src
```

If you have further questions you should ask [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repositories are for issues with the image and not necessarily for questions of usability

**Comment by mcandre** [comment]
Hi, while it is great that the `golang` image features an `alpine` tag, it is strange that `library/alpine:3.9`'s Go from the official Alpine package repository, is unable to run cleanly.

**Comment by tianon** [comment]
That's fair, but is an issue to file with Alpine, not us (the best we can do is what we provide in the image we maintain, we're not involved in the Alpine project much).
