### ISSUE TITLE
golang:1.11 latest (aka 1.11.12) error when copying file from container to linux host

### ISSUE THREAD

**Issue by obourdon** [docker-library/golang#292]
In our build process, one step uses golang:1.11 to do the following:
docker build -t c1 ...
docker cp c1:/prog ./bin

Docker file looks like:
```
FROM golang:1.11 AS builder
RUN go get -u GO_PROG
RUN mv /go/bin/prog /prog
```

Everything was fine until we moved (transparently in ou CI) from 1.11.11 to 1.11.12
where we got the following error:
```
...
Step 1/3 : FROM golang:1.11 AS builder
 ---> ee3ec9ac0398
Step 2/3 : RUN go get -u GO_PROG
 ---> Using cache
 ---> 5583e62a1146
Step 3/3 : RUN mv /go/bin/prog /prog
 ---> Using cache
 ---> c4b772ada7e7
Successfully built c4b772ada7e7
Successfully tagged prog-oubo3kahf1:latest
c594b46de9f1662f0c5acd64fadbc75d445dee127479b577ed601c30fe8ec2be
Error response from daemon: error processing tar file: docker-tar: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_readline_unlocked, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
: exit status 127
make[1]: *** [Makefile:77: bin/prog] Error 1
make: *** [Makefile:48: build] Error 2
```

Updating our Dockerfile to specify
```
FROM golang:1.11.11 AS builder
```
make the build be successful again

**Comment by wglambert** [comment]
Probably a mismatch in `libnss` or `libc6` versions, due to `1.11.12` using Debian Buster by default.

Your `1.11.11` version is still using Stretch, you can also specify `golang:1.11.12-stretch` to not use Buster, however it is the current stable release of Debian and so is the default variant

Using a tag that specifies the OS variant/version will help to prevent breakage https://github.com/docker-library/docs/tree/master/golang#supported-tags-and-respective-dockerfile-links

**Comment by obourdon** [comment]
@wglambert many thanks for confirming this. I have indeed updated the tag we use in our build process to prevent such breakage. However some other people might run into this slight regression using default tag like ourselves

**Comment by wglambert** [comment]
Closing since this is resolved
