### ISSUE TITLE
arm32v7 latest not able to be pulled down on amd64 for cross-compilation

### ISSUE THREAD

**Issue by NerdsvilleCEO** [docker-library/golang#304]
Not working: golang

```
josh@josh-manjaro-dev:docker-vim-go-tools $ docker run -it --rm -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static  arm32v7/golang:latest bash
Unable to find image 'arm32v7/golang:latest' locally
latest: Pulling from arm32v7/golang
docker: no matching manifest for linux/amd64 in the manifest list entries.
See 'docker run --help'.
```

Working: Alpine

```
josh@josh-manjaro-dev:docker-vim-go-tools $ docker run -it --rm -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static  arm32v7/alpine:latest ash
/ # 
```

**Comment by wglambert** [comment]
Docker has an experimental `--platform` feature for this, otherwise the it resolves to your current `linux/amd64` 
https://docs.docker.com/engine/reference/commandline/pull/

```console
$ docker version -f '{{.Server.Experimental}}'
true

$ docker pull --platform linux/arm/32v7 golang
Using default tag: latest
latest: Pulling from library/golang
2351e7f49dda: Pull complete 
871d6235d8c2: Pull complete 
bd4048754e16: Pull complete 
26c789eac1c8: Pull complete 
e85296c2d5bb: Pull complete 
ecdd0473dbba: Pull complete 
80af5c299762: Pull complete 
Digest: sha256:1b1246987ecb4939d9bd20f74eab25e8e2ad819aceea2d6b59869c82f85ef1de
Status: Downloaded newer image for golang:latest
```

**Comment by tianon** [comment]
This is a quirk because `golang:latest` is a "shared tag" so that Windows and Linux can live under the same tag via a manifest list, so it's always a manifest list regardless of the namespace it's pushed under: https://github.com/docker-library/official-images/blob/743a19657dfe9c824e9100806f1cd4d6f9db2072/library/golang#L8-L9

If you grab `arm32v7/golang:buster` or `arm32v7/golang:stretch` you should get a linux-only image.

See also https://github.com/docker-library/faq#whats-the-difference-between-shared-and-simple-tags for additional detail.
