### ISSUE TITLE
go get from private GitHub repository

### ISSUE THREAD

**Issue by spagettikod** [docker-library/golang#33]
Maybe this is obvious but I've been trying to find a solution for this for an hour or two without any success.

Trying to use golang:1.3.3-onbuild against my private repository fails with:
`fatal: could not read Username for 'https://github.com': No such device or address`

This comes as no surprise since I haven't stated any authentication anywhere. How do I authenticate to make go get work against a private repository?

**Comment by ns-cweber** [comment]
I'm having a similar problem, except my dependency is in the same repo as the service, just in a directory `../database` relative to the Dockerfile that needs it. I don't want to version it because I'm planning to rapidly iterate on the dependency and the service that needs it, and I don't want to have to update the vendor version all the time. I also can't make it a subdirectory of the service that uses it because there's another service that uses it as well. I'm not familiar with Docker, so maybe I'm missing something obvious?

**Comment by tianon** [comment]
You could use "-f" to specify the path to the "Dockerfile" inside the
sub-directory while allowing the context to remain the full repo one level
up, but that's the best solution I've got for that kind of requirement.

**Comment by zachgrayio** [comment]
@tianon The .godir trick is quite handy, though it took a bit of digging to come across it in relation to Golang+Docker issues, wondering if this is documented anywhere else? and if not, maybe it should be?

**Comment by tianon** [comment]
@zachgrayio we don't actually recommend `.godir` anymore (and it was never actually documented), since Go now supports "Custom Import Paths", which we lightly mention on https://hub.docker.com/_/golang/:
> (or `CMD ["myapp"]` if a [Go custom import path](https://golang.org/s/go14customimport) is in use)

Regardless, https://golang.org/s/go14customimport is a good read, and I highly recommend it.

**Comment by zachgrayio** [comment]
@tianon Awesome, I'll take a look, thanks for the infos!
