### ISSUE TITLE
go1.15.2 image builds appears to be hung waiting for next available executor on ‘multiarch-amd64’

### ISSUE THREAD

**Issue by justaugustus** [docker-library/golang#342]
Hi @tianon, can you take a look at this?
It appears that there are a few builds for go1.15.2 that have not been completed and I think they have been running for quite some time.

ref: https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/golang/252/console

This is currently blocking upstream Kubernetes Golang updates. (ref: https://github.com/kubernetes/release/pull/1533, https://github.com/kubernetes/kubernetes/pull/94449, https://github.com/kubernetes/release/issues/1517)

Thanks in advance! :)

**Comment by yosifkit** [comment]
That particular build is because Debian (https://github.com/docker-library/official-images/pull/8696) was merged and so all official-images `FROM` Debian are being rebuilt, but the golang update (https://github.com/docker-library/official-images/pull/8695) was merged before that and is already pushed to Docker Hub (with all available/supported architectures).

**Comment by justaugustus** [comment]
@yosifkit -- Thanks! Sorry for raising the alarm! :)
