### ISSUE TITLE
Include SSH for private git repos

### ISSUE THREAD

**Issue by jeffutter** [docker-library/golang#37]
It seems the golang images don't have ssh installed. This prevents using git to pull things from ssh repos not hosted with a git daemon.

Could ssh be added to the image?

I just found this issue: https://github.com/docker-library/golang/issues/33 which has valid points. My use case is using the golang image as a base in ci/cd system (drone), so I need to be able to pull from private repos.

**Comment by bradrydzewski** [comment]
I wonder if the Go image could inherit `buildpack-deps`. It's not uncommon for Go programs to link to C libraries, so I think such a change would fit the vision of `buildpack-deps`:

> In spirit, buildpack-deps is similar to Heroku's stack images. It includes a large number of “development header” packages needed by various things like Ruby Gems, PyPI modules, etc. For example, buildpack-deps would let you do a bundle install in an arbitrary application directory without knowing beforehand that ssl.h is required to build a dependent module.

I'm also a huge fan of consistency among the language stacks :)

**Comment by Moghedrin** [comment]
![grumpycat](https://cloud.githubusercontent.com/assets/1680823/5751629/c8a1703e-9c23-11e4-90c2-494274f8e1ec.png)

@jeffutter This is the perfect use case for building your own image on top of the official image. For the basic, general use case, this is unneeded overhead. Additionally, there's no good, general way to manage keys from the image, as even using -v flags to bindmount your keys inside the image will cause permission issues.

@bradrydzewski We're a fan of consistency among the language stacks, too, which is why we're consistently trying to get rid of buildpack-deps in favor of smaller, more concise images! :tada:

**Comment by tianon** [comment]
We could use the new micro build packs and get some shared layers that way!

**Comment by bradrydzewski** [comment]
@tianon yes, the `micro` image would be perfect.

This would increase the image size by 7MB, however, as mentioned gets us 64MB of shared layers with many other language stacks. @Moghedrin thoughts?

**Comment by Moghedrin** [comment]
:+1:

**Comment by tianon** [comment]
@proppy any thoughts you'd like to add here? :wink:

**Comment by proppy** [comment]
As long as micro-buildpack-deps stay under 10MB, that should be OK :)

will comment more on #38

**Comment by yograterol** [comment]
@jeffutter -1 SSH is a bad idea if you user Docker and @Moghedrin are right, you can do you own image for your software.

**Comment by bradrydzewski** [comment]
@yograterol for publishing and shipping containers I agree that using SSH would be a bad idea, since that would require embedding a private key. There are, however, multiple documented use cases for Docker where it makes sense:

* Continuous Integration services such as Drone, Circle CI, Shippable and Travis
* Development Environment services such as Cloud9, Nitrous and Codio
* Local development environments as an alternative to Vagrant

I think these use cases are especially well suited to the language stacks, by the way.

It is true that I can create my own images. In fact, many of the populate Docker services (Deis, Tutum, Drone, Nitrous, and more) already effectively maintain their own custom language stacks. I was hoping the official language stacks could unify these efforts. This would, however, mean sacrificing some megabytes for commonality.
