### ISSUE TITLE
Docker file: ADD package files from parent directory gives "no such file or directory" error

### ISSUE THREAD

**Issue by nikolasborrel** [docker-library/golang#40]
I have several local packages that my main application depends on, and I have problems setting up the Dockerfile in a correct way. When I ADD the parent directory I get "../shared-webservice/: no such file or directory". What's the problem here?

The Docker file:
ENV GOPATH /go/
ADD . /go/src/webservices/compute-webservice 
ADD ../shared-webservice/ /go/src/webservices/shared-webservice

RUN go install webservices/compute-webservice
RUN go install webservices/shared-webservice

ENTRYPOINT /go/bin/compute-webservice

The file structure:
go/
-- src/
---- webservices/
------ compute-webservice/
-------- main.go
-------- services/
---------- foo.go
------- shared-webservice
--------- foo.go

**Comment by proppy** [comment]
You can really do things like `ADD ../something)

Assuming your Dockerfile is in `src/webservices/compute-webservice` and is looking like this:
```
FROM golang

ADD go/src/webservices/compute-webservice /go/src/webservices/compute-webservice
ADD go/src/shared-webservice/ /go/src/webservices/shared-webservice

RUN go install webservices/compute-webservice # should build share-webservice deps

ENTRYPOINT /go/bin/compute-webservice
```


You have a few options:
- move shared-webservice a subpackage of compute-webservice
- vendor shared-webservice with Godeps or a similar tool
- use [docker-1.5.0-rc2](https://github.com/docker/docker/pull/10286) and call docker build from the root of your $GOPATH (not that your build context will contain all your GOPATH)
- build a custom context with something like
```
tar cvzf - $GOPATH/go/src/webservices/compute-webservice \
           $GOPATH/go/src/webservices/shared-webservice | docker build -
```

Hope that helps, closing since it's not really an issue with the image itself, but rather a limitation of docker that doesn't allow composing a build context from multiple directory.
