### ISSUE TITLE
Add linux/riscv64 as build target

### ISSUE THREAD

**Issue by 6543** [docker-library/golang#435]

**Comment by tianon** [comment]
The discussion on https://github.com/docker-library/php/issues/1279 is very relevant here (my answer would be very similar :sweat_smile:).

**Comment by 6543** [comment]
ok closing for now but still looking forward to get more adoption?

**Comment by olof-nord** [comment]
Came here looking for a riscv64 image too. So to summarise, once Debian has support, the golang docker project will consider building for riscv64 as well?

**Comment by tianon** [comment]
Yep!

**Comment by AlekSi** [comment]
"riscv64 is now an official Debian architecture": https://lists.debian.org/debian-riscv/2023/07/msg00053.html

**Comment by 6543** [comment]
@tianon :point_up: debian did it's move :)

**Comment by 6543** [comment]
https://hub.docker.com/layers/library/debian/unstable-slim/images/sha256-c6cea56c4b672c5bc3b43eeeebc3080ee1046834b359d1536a48b7a67dbee64b?context=explore

**Comment by tianon** [comment]
Correct, that means the process of rebuilding the archive for Debian Unstable is now underway, which is excellent news, but unfortunately only the first step towards this, not the last one.  Ideally this would've been included in the just-released Bookworm, but the relevant teams appear to have decided it'll be part of Trixie instead.

I'll also copy my (very relevant) note from https://github.com/docker-library/golang/issues/476#issuecomment-1642585635:

> having images based on Debian Unstable leads to a lot of not-unexpected instability both in our own builds and in the downstream builds of our users

**Comment by tianon** [comment]
> https://hub.docker.com/layers/library/debian/unstable-slim/images/sha256-c6cea56c4b672c5bc3b43eeeebc3080ee1046834b359d1536a48b7a67dbee64b?context=explore

That's still the debian-ports based image: https://explore.ggcr.dev/layers/debian@sha256:c6cea56c4b672c5bc3b43eeeebc3080ee1046834b359d1536a48b7a67dbee64b/etc/apt/sources.list.d/debian.sources

(I've been spending all day debating how/when to rebuild the Debian images and what to put in `sources.list` for riscv64 because we're now in this awkward place where debian-ports will no longer receive any updates, but it's the only place we have a full list of packages because the official archive rebuild is still WIP, and even just gcc alone likely won't be done building until Thursday, as I understand it from the folks working on it.)
