### ISSUE TITLE
golang 1.19.13 image

### ISSUE THREAD

**Issue by sbueringer** [docker-library/golang#488]
I hope this is the right place to open this issue.

I just saw that Go 1.19.13 was released (https://go.dev/doc/devel/release). Will there be a corresponding image for it?

**Comment by xrstf** [comment]
Since https://github.com/docker-library/golang/commit/5eba309 1.19 is considered end-of-life and was removed from this repo. The upstream announcement ( https://groups.google.com/g/golang-announce/c/Fm51GRLNRvM ) made it sound like 1.19.13 does not really contain anything too relevant:

> We have also released Go version 1.19.13, a minor point release that only includes fixes to improve its forward and backward compatibility.

So I would guess there will be no 1.19.13 images here.

**Comment by yosifkit** [comment]
For the supported images, we are just following upstream [Go's release policy](https://go.dev/doc/devel/release#policy):
>Release Policy
>Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. We fix critical problems, including [critical security problems](https://go.dev/security), in supported releases as needed by issuing minor revisions (for example, Go 1.6.1, Go 1.6.2, and so on).

So, if upstream Go releases a patch for a version outside the two latest major releases, I am not opposed to adding it temporarily for that single patch release. I'll work up a PR.

**Comment by sbueringer** [comment]
Thank you!
