### ISSUE TITLE
Tags keep flip-flopping between two digests

### ISSUE THREAD

**Issue by RichardoC** [docker-library/golang#515]
I maintain kube-audit-rest and I'm using [rennovate](https://github.com/renovatebot/renovate) to watch for any changes on my dependencies and raise a PR to update my project when required. I'm also pinning all used container images to specific digests rather than using tags.

As you can see on <https://github.com/RichardoC/kube-audit-rest/pull/123> certain tags such as golang:1.22.1-alpine3.19 and golang:1.22.2-alpine3.19 <https://github.com/RichardoC/kube-audit-rest/pull/133> keep flip flopping between two stable digests.

I'm not sure exactly how these are pushed given there seem to be both github actions and a Jenkins server in use for this project but mind having a look and seeing if you can prevent this flip-flopping? It's causing quite a lot of noise for me, and I want to continue to get the benefit of being able to update to the latest digest whenever a tag is updated (for example with security updates)

Thanks!

**Comment by tianon** [comment]
Looking at the history on https://github.com/docker-library/repo-info/blob/master/repos/golang/remote/1.22.2-alpine3.19.md, I don't see the flip-flopping (in fact, just the tag creation two days ago and no touches to it since, which matches what I'd expect).  It _is_ possible though that the job which generates that keeps missing the flip-flopping. :thinking:

The tag at `golang:1.22.1-alpine3.19` should now be completely stable because it's fully unsupported and will not be updated again unless Go upstream does something unprecedented like re-releasing 1.22.1. :smile:

Looking at https://github.com/RichardoC/kube-audit-rest/pull/133, though, I see exactly what's happening -- Rennovate can't seem to decide whether it should pin to the top-level index digest or the amd64-specific one.

To see what I mean, compare the top-level digest of https://oci.dag.dev/?image=golang:1.22.2-alpine3.19@sha256:cdc86d9f363e8786845bea2040312b4efa321b828acdeb26f393faa864d887b0 and the digest of the first entry in the `manifests` array with the two in that Rennovate PR.

**Comment by RichardoC** [comment]
Aha, thank you for the investigation! I'll report that to them and hopefully prevent others making the same mistake

**Comment by RichardoC** [comment]
Moved to <https://github.com/renovatebot/renovate/discussions/28252>
