### ISSUE TITLE
armv5(arm32v5) and armv6(arm32v6) images for 1.22 branch

### ISSUE THREAD

**Issue by d3vilh** [docker-library/golang#523]
Hi folks, 
do you have plans to build `arm32v6` or `arm32v5` `bookworm` images of `1.22.x` branch for Docker Hub? 
I keep maintaining Raspberry-Pi Zero compatible images for my projects and updated GoLang image would be very useful.

```shell
slava@ukraine:~/build $ docker pull arm32v6/golang:1.22.3-bookworm
Error response from daemon: manifest for arm32v6/golang:1.22.3-bookworm not found: manifest unknown: manifest unknown
slava@ukraine:~/build $
```
Thanks!

**Comment by yosifkit** [comment]
The `1.20` series was the last we could support on `arm32v5`. See this [comment on #500](https://github.com/docker-library/golang/pull/500#issuecomment-1863578601) for more details. To get an `arm32v6` image, you need use an `alpine` tag because the Debian OS architectures are only `v5` or `v7`.

Alternatively, you might consider cross compiling your go-based project on a common `amd64` host and then inject it (`COPY --from`) into an `arm32v5` or `v6` image.

Similar to https://github.com/docker-library/golang/issues/502

**Comment by d3vilh** [comment]
Thanks a lot for the explanation.
