### ISSUE TITLE
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found while using cloudnativepg on top of fdw

### ISSUE THREAD

**Issue by sadathknorket** [docker-library/golang#534]
Here is the error 

```
ERROR:  could not load library "/usr/lib/postgresql/15/lib/steampipe_postgres_aws.so": /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/lib/postgresql/15/lib/steampipe_postgres_aws.so)
```

I have the following Dockerfile for running postgres fdw 

```sh
# Stage 1: Building the Go executable
FROM golang:1.22.2-bookworm AS build

WORKDIR /build

COPY ./ .

RUN go build -o main main.go

# Final image
FROM postgres:15

ENV TERM=xterm

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*

COPY install_fdw.sh /tmp/
RUN /tmp/install_fdw.sh && \
    rm /tmp/install_fdw.sh


COPY --from=build /build/main /
COPY --from=build /build/init.sh /docker-entrypoint-initdb.d
```

I decided to shift to ```cloudnativepg```

and tried using ```postgres``` image with ```ghcr.io/cloudnative-pg/postgresql:15```

Its very hard and error prone to upgrade ```GLIBC``` and I still did not succeed . Is there any other smart solution in place here?

I know this might not be much related to here but I see you have experience in resolving similar issues any help or suggestions would be great here , thanks

**Comment by yosifkit** [comment]
That sounds like the `steampipe_postgres_aws.so` installed by `install_fdw.sh` is built/linked against too new of a glibc for the OS that you are trying to put it in (since `ghcr.io/cloudnative-pg/postgresql:15` is only Debian Bullseye based). If you are really using the `postgres:15` image, then it shouldn't have an issue, since it is Debian Bookworm based (and thus is new enough for `GLIBC_2.32`).
